name: sleed_task_manager_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.5
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  toast: ^0.3.0
  provider: ^6.1.2
  firebase_core: ^3.8.0
  url_launcher: ^6.3.1
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.3
  logging: ^1.3.0
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  flutter_timezone: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4

flutter:
  assets:
    - images/
  uses-material-design: true